### ISSUE TITLE
why Big Sur only?

### ISSUE THREAD

**Issue by foxnoodles** [Dimillian/RedditOS#23]
Any reasoning behind this? How hard is to compile it for lower OS(rhetorical question)

**Comment by Dimillian** [comment]
Yes, the SwiftUI features it uses are only available on Big Sur.

**Comment by foxnoodles** [comment]
Which features exactly, I just want to understand why are those so crucially important to use over Millions of potential Mojave and Catalina users.

**Comment by omfgnuts** [comment]
@foxnoodles SwiftUI features, bruh

**Comment by foxnoodles** [comment]
> @foxnoodles SwiftUI features, bruh

Well Bruh... what exactly stops him from compiling for Mojave or Catalina bruh? SwiftUI runs fine on those... if you mean the development side (previews and canvas) you could do it on Catalina too so what's the deal Bruh? Enlighten me Bruh...

**Comment by Dimillian** [comment]
There is so many things in the SwiftUI version of Big Sur that I can't even begin to list them. There is toolbar support, proper NavigationView support, all the new SF Symbols and so on. It's a bleeding edge app for the most updated version of macOS. I have 0 incentive to make or maintain an app for an older version of it. Deal with it.

**Comment by foxnoodles** [comment]
Dude your 8 yr old or something? Deal with it? Woaah that's so raaad... nobody cares about your bleeding ass app. At least 50% of Mac users to be exact so chill you haven't even made it yet.

**Comment by TheVaan** [comment]
In German I would ask: Kann das sein, dass du dumm bist?

This is an open source project, done in @Dimillian's free time. It is a project to demonstrate SwiftUI on Mac OS (read the README.md). I don't know why there is a dude blaming an other dude for not supporting what he wants. 
I've an advise for you: develop your own version of the app matching your needs.

**Comment by ericlewis** [comment]
@foxnoodles feel free to open a PR targeting lower macOS versions, we’ll be waiting.

**Comment by interstateone** [comment]
> what exactly stops him from compiling for Mojave

if I recall correctly you can run SwiftUI in the _iOS 13_ simulator (and so you could use Previews too) in Xcode 11 on Mojave, but SwiftUI on _macOS_ targets 10.14 Catalina. So I don't think this is an option at all.

> or Catalina

As the author already mentioned, there is a bunch of new API in SwiftUI on Big Sur, as well as behaviour changes. I'm not sure if you've done any SwiftUI development yet, but the API and behaviour has changed a lot on all of the platforms (much more than most Apple APIs do) since it was first released. This is good, because a lot of bugs are being fixed and improvements are being made, but also bad because it takes a lot of work as a developer to keep up, let alone also maintain backwards compatibility. For a project like this, I would imagine that means the difference between the project existing at all or not. It is not simply a matter of flipping the Catalina switch to on.

---

@foxnoodles, I really hope you can take a step back and reconsider how you're talking to other people in this thread. This project is one of the few open source examples of an entire SwiftUI app on macOS. I'm not involved with it at all, but I've been referencing it as I work on my own SwiftUI on macOS project (which also targets Big Sur, for the same reason). It's been provided free of charge, and you're not owed anything. If you genuinely want to discuss how to handle backwards compatibility with SwiftUI on macOS, or learn how you can contribute to this project to improve something, now's your chance. Otherwise it would save everyone here a lot of time if you just dropped it.

**Comment by foxnoodles** [comment]
> Kann das sein, dass du dumm bist?

In Georgian I would reply: "მოგიტყან ნაცისტი დედის მუტელი" ...as nobody cares about your language here

Speaking of stupidity, I'm no asking to support what I want mr. braindead. I'm rhetorically implying that no matter what this project is trying to achieve it does not make any sense when it ignores the majority of user-base. And btw "make your own" "code your own" answers are like from 2000s... You should really grow up. I don't have nor will I code anything to prove my point lol. You are literally following the Reddit client issue comments, acting like a Reddit Monkey yet you claim you haven't visited it for 3 years. Right.. also downvotes are for morons who think that actual living human beings care about them. You being one of those. Now square.





> > what exactly stops him from compiling for Mojave
> 
> if I recall correctly you can run SwiftUI in the _iOS 13_ simulator (and so you could use Previews too) in Xcode 11 on Mojave, but SwiftUI on _macOS_ targets 10.14 Catalina. So I don't think this is an option at all.
> 
> > or Catalina
> 
> As the author already mentioned, there is a bunch of new API in SwiftUI on Big Sur, as well as behaviour changes. I'm not sure if you've done any SwiftUI development yet, but the API and behaviour has changed a lot on all of the platforms (much more than most Apple APIs do) since it was first released. This is good, because a lot of bugs are being fixed and improvements are being made, but also bad because it takes a lot of work as a developer to keep up, let alone also maintain backwards compatibility. For a project like this, I would imagine that means the difference between the project existing at all or not. It is not simply a matter of flipping the Catalina switch to on.
> 
> @foxnoodles, I really hope you can take a step back and reconsider how you're talking to other people in this thread. This project is one of the few open source examples of an entire SwiftUI app on macOS. I'm not involved with it at all, but I've been referencing it as I work on my own SwiftUI on macOS project (which also targets Big Sur, for the same reason). It's been provided free of charge, and you're not owed anything. If you genuinely want to discuss how to handle backwards compatibility with SwiftUI on macOS, or learn how you can contribute to this project to improve something, now's your chance. Otherwise it would save everyone here a lot of time if you just dropped it.

Thanks for the actual explanation. I was actually wondering if there are any major additions to the newest SwiftUI that lead to the decision of targeting the 1 month old OS (which has arguably the worst adoption rate since Yosemite) and completely losing any traction before even having a stable release. The reason behind my curiosity is to determine how serious the author is about his intentions to develop and maintain an actual product and judging by the audience and authors attitude and product design vision I pretty sure this won't get anywhere big.

As for "something being free on github so nobody should complain about it " - I certainly disagree with that mindset and trust me once you get traction with your project you as a product owner are morally obligated to listen to your user-base. Or else you will lose them.  That's why stuff like Blender exists and BigSur only Reddit Clients don't.

Also as you probably noticed I can change my tone of voice freely at any time, it just depends who and how replies back.  I don't tolerate the "deal with it bruh" garbage in any shape or form both in virtual and IRL when it goes to serious talk abou subjects like why the fuck have you decided to target a mass product to 1 months old os only. and I do thing it's what every sane human being should do. 

That being said not that I care about "bruh deal with it and here's the thumbs down" kind of infantile beta males time but I do care about yours and mine so Imma close this one. Happy new year btw.
