### ISSUE TITLE
-

### ISSUE THREAD

**Issue by fb2e23b7-d556-421d-8885-72b9261eb5d8** [Dimillian/RedditOS#38]

**Comment by capaldo** [comment]
Please provide a screenshot of what you're referring to.

**Comment by simjnd** [comment]
@mimetism I've redrawn the icon so that it looks like a little bit like some macOS Big Sur stock ones. It is the exact same size as the stock apps' icons, if it bothers you too much you can [try it out (MEGA, 1.1 MB)](https://mega.nz/file/9ZwlVCTY#sLiNKyTIIstfJT_nxOYL558R92zXoa0LZvJx1LLgXdY).

![icon_512x512](https://user-images.githubusercontent.com/43272781/127210841-33cfa2b0-166b-446e-9cae-e5d2297924ba.png)
